version: '3'
services:
  db-api:
    image: prismagraphql/prisma:1.17.2
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: db
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    healthcheck:
      test: echo exit | telnet localhost 4466

  db:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
    - postgres2:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
    - NODE_ENV=development
    - PRISMA_API_HOST=db-api:4466
    env_file:
      - .env
    volumes:
    - ./node_modules:/opt/app/node_modules:ro
    - ./src:/opt/app/src:ro
    - ./src/generated:/opt/app/src/generated
    - ./datamodel.prisma:/opt/app/datamodel.prisma:ro
    - ./schema.graphql:/opt/app/schema.graphql:ro
    ports:
    - "4000:4000"
    - "9230:9230"

  adminer:
    image: clue/adminer
    ports:
    - "4001:80"

volumes:
  postgres2:
