version: '3'
services:
  db-api:
    image: prismagraphql/prisma:1.21
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: db
            port: 5432
            user: prisma
            password: prisma
            migrations: true
    healthcheck:
      test: echo exit | telnet localhost 4466

  db:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
    - postgres2:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
    - NODE_ENV=development
    - PRISMA_API_HOST=db-api:4466
    - AUTH_DOMAIN=uplus-example-app.eu.auth0.com
    - AUTH_CLIENT_ID=OLFC6zI1Wjv70da049XJNoRhRlwNUZQV
    - AUTH_AUDIENCE=uplus-example-app
    - AUTH_JWKS_URL=https://uplus-example-app.eu.auth0.com/.well-known/jwks.json
    - AUTH_CUSTOM_CLAIMS_NS=uplus-example-app
    - AUTH_ADMIN_CLIENT_ID=ocj75tD0tUhF6NgtH8ZCMOZlEZDYVLSg
    - AUTH_ADMIN_CLIENT_SECRET=GWCgbwmKOQppCTlHKuwRdXegI-nZMHZG3G0IWowhD6vIoYxr44T9bmscrGGNQTpS
    volumes:
    - ./src:/opt/app/src:ro,delegated
    - ./src/generated:/opt/app/src/generated:delegated
    - ./datamodel.prisma:/opt/app/datamodel.prisma:ro,delegated
    - ./schema.graphql:/opt/app/schema.graphql:ro,delegated
    ports:
    - "4000:4000"
    - "9230:9230"

  adminer:
    image: clue/adminer
    ports:
    - "4001:80"

volumes:
  postgres2:
